In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Roqmes-tavha0-tirnan@localhost/phonepe_pulse"
)

In [2]:
q1 = """
SELECT state, SUM(txn_amount) AS total_amount
FROM aggregated_transaction
GROUP BY state
ORDER BY total_amount DESC
LIMIT 10;
"""
df_q1 = pd.read_sql(q1, engine)
df_q1

            state  total_amount
0       Telangana  4.165596e+13
1       Karnataka  4.067872e+13
2     Maharashtra  4.037420e+13
3  Andhra Pradesh  3.466908e+13
4   Uttar Pradesh  2.688521e+13
5       Rajasthan  2.634324e+13
6  Madhya Pradesh  1.912528e+13
7           Bihar  1.790135e+13
8     West Bengal  1.558416e+13
9          Odisha  1.226398e+13

In [3]:
q2 = """
SELECT transaction_type, SUM(txn_count) AS total_txns
FROM aggregated_transaction
GROUP BY transaction_type
ORDER BY total_txns DESC;
"""
pd.read_sql(q2, engine)

           transaction_type    total_txns
0         Merchant payments  1.302388e+11
1     Peer-to-peer payments  8.503245e+10
2  Recharge & bill payments  1.959676e+10
3                    Others  2.620502e+08
4        Financial Services  1.542089e+08

In [4]:
state_name = "Karnataka"

q3 = f"""
SELECT district, SUM(txn_amount) AS total_amount
FROM map_transaction
WHERE state = '{state_name}'
GROUP BY district
ORDER BY total_amount DESC
LIMIT 10;
"""
pd.read_sql(q3, engine)

                   district  total_amount
0  bengaluru urban district  1.993784e+13
1           mysuru district  1.646375e+12
2         belagavi district  1.341643e+12
3  bengaluru rural district  1.218275e+12
4         tumakuru district  1.166001e+12
5          ballari district  1.058659e+12
6       kalaburagi district  9.791941e+11
7            kolar district  9.482292e+11
8          dharwad district  9.276930e+11
9           hassan district  8.035883e+11

In [5]:
q4 = """
SELECT state,
       SUM(registered_users) AS users,
       SUM(app_opens) AS app_opens
FROM map_user
GROUP BY state
ORDER BY users DESC
LIMIT 10;
"""
pd.read_sql(q4, engine)

            state         users     app_opens
0     Maharashtra  1.140138e+09  4.961642e+10
1   Uttar Pradesh  9.423341e+08  3.323683e+10
2       Karnataka  7.336742e+08  3.834488e+10
3  Andhra Pradesh  5.567471e+08  2.472802e+10
4       Rajasthan  5.557745e+08  4.850763e+10
5     West Bengal  5.249644e+08  1.094382e+10
6       Telangana  5.246205e+08  2.319777e+10
7      Tamil Nadu  5.064868e+08  1.699220e+10
8  Madhya Pradesh  4.706636e+08  3.970850e+10
9         Gujarat  4.591547e+08  2.078042e+10