In [1]:
import os
import json
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
BASE_PATH = r"D:\\pulse\\data\\aggregated\\user\\country\\india\\state\\"

In [3]:
state = os.listdir(BASE_PATH)[0]
year = os.listdir(os.path.join(BASE_PATH, state))[0]
file = os.listdir(os.path.join(BASE_PATH, state, year))[0]

with open(os.path.join(BASE_PATH, state, year, file), "r", encoding="utf-8") as f:
    data = json.load(f)

data["data"].keys()

dict_keys(['aggregated', 'usersByDevice'])

In [4]:
rows = []

for state in os.listdir(BASE_PATH):
    state_path = os.path.join(BASE_PATH, state)
    if not os.path.isdir(state_path):
        continue
        
    for year in os.listdir(state_path):
        for file in os.listdir(os.path.join(state_path, year)):
            if not file.endswith(".json"):
                continue
                
            quarter = int(file.replace(".json", ""))
            with open(os.path.join(state_path, year, file), "r", encoding="utf-8") as f:
                content = json.load(f)

            aggregated = content["data"].get("aggregated")
            if not aggregated:
                continue

            for device in aggregated.get("usersByDevice", []):
                rows.append({
                    "state": state.replace("-", " ").title(),
                    "year": int(year),
                    "quarter": quarter,
                    "brand": device["brand"],
                    "user_count": device["count"],
                    "percentage": device["percentage"]
                })

df_agg_user = pd.DataFrame(rows)
df_agg_user.head()

Empty DataFrame
Columns: []
Index: []

In [5]:
engine = create_engine(
    "mysql+mysqlconnector://root:Roqmes-tavha0-tirnan@localhost/phonepe_pulse"
)

create_table = """
CREATE TABLE IF NOT EXISTS aggregated_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    brand VARCHAR(100),
    user_count BIGINT,
    percentage DOUBLE
);
"""

with engine.connect() as conn:
    conn.execute(text(create_table))
    conn.commit()

In [6]:
df_agg_user.to_sql(
    "aggregated_user",
    con=engine,
    if_exists="append",
    index=False
)

0

In [7]:
pd.read_sql("SELECT * FROM aggregated_user LIMIT 5", engine)

Empty DataFrame
Columns: [id, state, year, quarter, brand, user_count, percentage]
Index: []